version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      commit-message:
          prefix: chore
      reviewers:
          - '@Evoke-Platform/evoke-team'
    - package-ecosystem: npm
      directory: /packages/plugin
      ignore:
          - dependency-name: yeoman-test # v7 is ESM only
            update-types: [version-update:semver-major]
      schedule:
          interval: weekly
      commit-message:
          prefix: chore
      reviewers:
          - '@Evoke-Platform/evoke-team'
    - package-ecosystem: npm
      directory: /packages/plugin/src/generators/app/templates
      schedule:
          interval: weekly
      commit-message:
          prefix: chore
      reviewers:
          - '@Evoke-Platform/evoke-team'
    - package-ecosystem: npm
      directory: /packages/sdk
      schedule:
          interval: weekly
      commit-message:
          prefix: chore
      reviewers:
          - '@Evoke-Platform/evoke-team'
