image: node:18

pipelines:
    default:
        - step:
              name: Build
              caches:
                  - node
              script:
                  - yarn install
                  - yarn test
                  - yarn lint
    branches:
        main:
            - step:
                  name: Deploy
                  deployment: test
                  caches:
                      - node
                  script:
                      - npm config set //registry.npmjs.org/:_authToken ${NPM_REGISTRY_TOKEN}
                      - yarn install
                      - git tag baseline HEAD^
                      - yarn build --filter=...[baseline]
                      - npx turbo run release --concurrency 1 --filter=...[baseline] -- --prerelease dev --skip.tag --skip.changelog
                      - npx turbo run deploy --filter=...[baseline] -- --tag dev
                      - git pull --no-rebase
                      - git push
        release:
            - step:
                  name: Deploy
                  deployment: production
                  caches:
                      - node
                  script:
                      - npm config set //registry.npmjs.org/:_authToken ${NPM_REGISTRY_TOKEN}
                      - git fetch origin refs/tags/latest:origin/refs/tags/latest
                      - yarn install
                      - yarn build --filter=...[latest]
                      - npx turbo run release --concurrency 1 --filter=...[latest]
                      - npx turbo run deploy --filter=...[latest]
                      - git tag -f latest
                      - git push -f origin refs/tags/latest
                      - git pull --no-rebase
                      - git push --follow-tags
