image: node:18

pipelines:
    default:
        - step:
              name: Build
              caches:
                  - node
              script:
                  - npm install
                  - npm run test
                  - npm run lint
    branches:
        main:
            - step:
                  name: Deploy
                  deployment: test
                  caches:
                      - node
                  script:
                      - npm config set //registry.npmjs.org/:_authToken ${NPM_REGISTRY_TOKEN}
                      - npm install -g npm-auto-snapshot
                      - grep SNAPSHOT package.json
                      - if [ $? = 0 ]; then npm_update_snapshot; TAG=dev; else npm_check_no_snapshots; TAG=latest; fi
                      - npm install
                      - npm run build
                      - npm publish --tag $TAG
